#ifndef CONFIG_H
#define CONFIG_H

/* FS root inode number */
#define ROOT_DIR_INUM (0)

#define BLOCK_SIZE (1024)
#define DATA_BLOCKS (1024)
#define INODE_TABLE_SIZE (50)
#define MAX_OPEN_FILES (20)
#define MAX_FILE_NAME (40)

#define DELAY (5000)

#define INODE_DIRECT_ENTRIES 10
#define INODE_INDIRECT_ENTRIES 1
#define BLOCKS_IN_A_INDIRECT_BLOCK (BLOCK_SIZE/4)
#define INODE_SIZE_AVAILABLE (INODE_DIRECT_ENTRIES*BLOCK_SIZE + INODE_INDIRECT_ENTRIES*BLOCKS_IN_A_INDIRECT_BLOCK*BLOCK_SIZE)

#define ERROR -1
#define NOT_ALLOCD -1

#endif // CONFIG_H
